version: '3.1'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mgm_withdrawals'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user_app'
    ports:
      - '5432:5432'
  api:
    build:
      context: .
      dockerfile: DockerfileBuilder  # Specify your custom Dockerfile name here
    container_name: wezaam-challenge-be
    image: wezaam-challenge-be:latest
    environment:
      - DATABASE_URL=postgres
    ports:
      - "7070:7070"
    depends_on:
      - postgres